### ISSUE TITLE
Markers found as signif get missing after alignment

### ISSUE THREAD

**Issue by HanXiaoEvo** [INRA-LPGP/RadSex#28] opened 2022-10-11 19:36 UTC
Hi there,

This might be a naive question. 

I got 13 markers as significant with min depth of 5.  However, when I ran the radsex --map to align the markers, only 9 of  13 remained, so 4 were missing. I tried to remove the mapping quality flag and min-frequency flag (only min depth of 5 was kept) but got the same results. Since I have pair-end reads concatenated so I tested if it correlates with the reverse read. I found all of the 4 missing ones were reverse reads, however, for the remaining ones there are also reverse reads.

So what might be the reason for this? Simply no mapping? How can I check the mapping of only the missing marker? Thank you very much!

Best regards,
Han

**Comment by RomainFeron** [comment] 2022-10-13 09:41
Hi Han,

It's difficult to say without seeing the data but my guess is that these markers were either not aligned at all as you said or they were aligned to multiple positions in the genome with the same mapping score (these reads are also discarded).

Just to be sure, do you mean that your reads are concatenated paired-ends, meaning the reads are chimeric? In general RADSex was designed for with single-end reads because of how the basic algorithm works. Paired-end reads work but only reads coming from the restriction enzyme cutting sites will actually be useful, and paired reads will just add noise (assuming the insert size is variable).

Let me know if this was helpful and don't hesitate if you have further questions!

Cheers,
Romain

**Comment by HanXiaoEvo** [comment] 2022-10-13 13:45
Hi Romain,

Thank you for your help! I forgot to mention that my data was generated using ddRAD, so two enzymes were used and certain fragment length were chosen. Therefore there should be no problem regarding the standardization of all the reads (one cutting cite per end and same length).  

I guess it is difficult to check this point, so I will leave it for now. I also have another question regarding the significant test. I know the original objective of the design was to find SD markers. However, I am using it to compare potential SD-related variations across different populations of the same species (similar to Pan 2021, the northern pike master SD gene paper). I may find one marker being significant in one population, but not in the other, how should I explain this? I know it may be beyond the scope but I will really appreciate your suggestions. If here is not the proper location to discuss that I can switch to the email. Thank you very much!

Cheers,
Han

**Comment by HanXiaoEvo** [comment] 2022-10-13 16:10
Hi Romain,

I get a quick practical question, which may also interest some others. I am checking the situation of significant SD markers unique to some populations in the other populations that don't get these markers significant and like to know how many male/female have it, mostly the idea will be to visualize it in the tile plot. 

I thought I can first check the presence/absence of the specific reads/markers in the target population by "grep" the reads in the table.tsv. Then I extract the reads (if there) to make a fake table.tsv file and to use it as the input to run rasex --distrib. I modified the number of markers in the fake files but got the error: Floating point exception (core dumped). I am wondering is it possible to run what I like in RADSex? Or if you can share any ideas on how to make a simple script to do so (sry I am not so good at it)?

Thank you very much!

Cheers,
Han

**Comment by RomainFeron** [comment] 2022-10-14 12:37
Hi Han,

It should be fine indeed with a fixed insert size :) 

The significance test in RADSex is very stringent. It's correction p-values using Bonferroni based on the total number of markers tested (which depends on minimum depth). With a high sample size and very clean signal usually it doesn't matter too much but with more patchy data sometimes it's a bit more difficult to call what is significant or not, especially when you want to compare datasets like you are doing. It's possible to find a marker significant in a population but not in another if sample size is different between the two populations, or if there are some differences in sequencing (depth, sequencing artefacts introducing a lot of low-depth markers etc...). If this is happening, there are several things you could try: first, it's interesting to check if the markers that are not significant in some populations are still associated with sex in these populations. This would be a good thing, because then it's likely just a matter of stringency because of the factors I mentioned above. In this case, you could still consider these markers associated with sex, just not significantly according to the test used. You could also try running RADSex without correcting p-values and computing association test yourself with a less stringent correction (you can use the number of males / females in the results file for that for instance). If you want to discuss further on what you are doing and your project, I agree it's probably better to use email for that :)

Regarding your second question, it's a good point and I've already had requests to implement a command to extract a subset of reads from their ID, I think that would be useful in your case. I will see if I can implement something like that but it's difficult for me to find the time to work on it at the moment. In the meantime, I will test the solution you tried to see if I get the same error. I think it should work in theory and the error might come from a formatting error in the fake table.tsv. I'll let you know soon if I managed to do it and I can share what I did then.

**Comment by HanXiaoEvo** [comment] 2022-10-17 09:55
Hi Romain,

Thanks a lot again for your helpful suggestions! Yes as you said I extracted the significant markers found in each pop and check how they present in the F&M from other pops. I do find some tend to be male associated (although less than all), so taking what you said we can have a loose conclusion that there may not be too much pop-level difference.

And I tried to extract the makers I am interested in and then make a fake table.tsv for distrib, It worked when I change the way to pack the makers. What I found is the program is not ID sensitive so I don't need to replace the messy uncontinues ID, which is less work. I guess it is the top line that matters. Anyway thank you soooo much for all the help and for making this program! I will contact via email if I have more specific questions!

Best,
Han

**Closed as completed** 2023-03-09 08:48 UTC
